---
before:
  hooks:
    - go mod download
    - go mod verify
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
nfpms:
  - formats:
      - deb
    homepage: "https://github.com/retailnext/multihealthcheck"
    license: "Apache 2.0"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore\(ci\):'
      - '^chore\(deps\):'
      - '^docs:'
      - '^test:'
